### PR TITLE
update wampy.d.ts to work with in-browser typescript

### PR DESCRIPTION
**Pull request by haswelldev**
I'm not sure if this change may affect node-js (should not) but it makes wampy to work perfectly in browser:

```bash
typings install dt~wampy
```
and then
```bash
import * as Wampy from 'wampy'
```

Also updated arguments in callbacks to support wampy v4.*

### CODE REVIEW

**Comment by KSDaemon** [comment]
Hi! Thanks for ur update! I'm not a ts guru. So, i hope your structural changes are ok! :)

**Comment by KSDaemon** [comment]
Well... unfortunately tests failed.... You can run npm test.

```=============================================================================
                    Errors in files
=============================================================================
----------------- For file:wampy/wampy-tests.ts
wampy/wampy-tests.ts(4,8): error TS1192: Module ''wampy'' has no default export.
wampy/wampy-tests.ts(27,49): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(30,44): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(40,26): error TS7006: Parameter 'stime' implicitly has an 'any' type.
wampy/wampy-tests.ts(44,24): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(61,22): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(65,40): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(68,26): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(71,24): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(77,26): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(80,24): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(86,26): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(89,24): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(103,26): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(106,24): error TS7006: Parameter 'err' implicitly has an 'any' type.
wampy/wampy-tests.ts(114,26): error TS7006: Parameter 'data' implicitly has an 'any' type.
wampy/wampy-tests.ts(117,24): error TS7006: Parameter 'err' implicitly has an 'any' type.```

**Comment by KSDaemon** [comment]
@421p so i temporary reverted ur change. Please fix errrors, so npm test will success and then create a pr again. With failed tests i can not pr it to dt repo

**Comment by haswelldev** [comment]
@KSDaemon woops i totally forgotten about tests :sweat_smile: 
[https://github.com/KSDaemon/DefinitelyTyped/pull/3](https://github.com/KSDaemon/DefinitelyTyped/pull/3)

**Pull request merged**
